/** @format */

const ActionType = {
  GETDATA: "@TABLE/GETDATA",
  LOADING: "@GLOBAL/LOADING",
  ERROR: "@GLOBAL/ERROR",
  ADDCOUNTRY: "@ADD/COUNTRY",
  DELETECOUNTRY: "@DEL/COUNTRY",
  EDITDETAILS: "@EDIT/DETAILS",
  ASCENDING: "@SORT/ASCENDING",
  DESCENDING: "@SORT/DESCENDING",
  FILTERNAME: "@FILTER/COUNTRYNAME",
};

export default ActionType;
